services:
  ufotablecorp:
    build: .
    container_name: ufotablecorp_http
    ports:
      - "8081:80"
    volumes:
      # Config de Apache para este servidor
      - ./config/ufotablecorp.conf:/etc/apache2/sites-enabled/000-default.conf:ro

      # DocumentRoot /var/www/ufotablecorp/html
      - ./html/ufotablecorp:/var/www/ufotablecorp/html:ro

      # Alias /images â†’ /var/www/ufotablecorp/images
      - ./html/ufotablecorp/images:/var/www/ufotablecorp/images:ro

      # Logs /var/www/ufotablecorp/logs
      - ./logs/ufotablecorp:/var/www/ufotablecorp/logs
    restart: unless-stopped

  ufotablemll:
    build: .
    container_name: ufotablemll_http
    ports:
      - "8082:80"
    volumes:
      - ./config/ufotablemll.conf:/etc/apache2/sites-enabled/000-default.conf:ro

      - ./html/ufotablemll:/var/www/ufotablemll/html:ro
      - ./html/ufotablemll/images:/var/www/ufotablemll/images:ro

      - ./logs/ufotablemll:/var/www/ufotablemll/logs
    restart: unless-stopped
